services:
  - type: web
    name: ytdl
    env: node
    buildCommand: node -v && npm install
    startCommand: nodemon index.js
    envVars:
      - key: NODE_VERSION
        value: 14
      - key: WASABI_ACCESS_KEY_ID
        sync: false
      - key: WASABI_SECRET_ACCESS_KEY
        sync: false
