services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 14
      - key: WASABI_ACCESS_KEY_ID
        sync: false
      - key: WASABI_SECRET_ACCESS_KEY
        sync: false
